import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import IncidentType from 'App/Models/IncidentType'

export default class IncidentTypeSeeder extends BaseSeeder {
  public async run () {
    await IncidentType.createMany([
      { code: 'robo_sin_violencia', name: 'Robo sin violencia' },
      { code: 'robo_con_violencia', name: 'Robo con violencia' },
      { code: 'asalto_armado', name: 'Asalto armado' },
      { code: 'intento_de_robo', name: 'Intento de robo' },
      { code: 'acoso_callejero', name: 'Acoso callejero' },
      { code: 'persecucion_sospechosa', name: 'Persecución sospechosa' },
      { code: 'peleas_en_via_publica', name: 'Peleas en vía pública' },
      { code: 'intento_de_secuestro', name: 'Intento de secuestro' },
      { code: 'vandalismo_cercano', name: 'Vandalismo cercano' },
      { code: 'persona_agresiva', name: 'Persona agresiva o alterada' },
      { code: 'ataque_de_perro', name: 'Ataque de perro' },
      { code: 'perro_agresivo_suelto', name: 'Perro agresivo suelto' },
      { code: 'ataque_de_animales_salvajes', name: 'Ataque de animales salvajes' },
      { code: 'enjambre_de_abejas', name: 'Enjambre de abejas o insectos peligrosos' },
      { code: 'animal_muerto_en_via_publica', name: 'Animal muerto en vía pública' },
      { code: 'atropello', name: 'Atropello' },
      { code: 'casi_atropello', name: 'Casi atropello' },
      { code: 'vehiculo_exceso_velocidad', name: 'Vehículo a exceso de velocidad' },
      { code: 'vehiculo_sospechoso_siguiendo', name: 'Vehículo sospechoso siguiendo a la persona' },
      { code: 'conductor_agresivo', name: 'Conductor agresivo' },
      { code: 'motocicleta_en_banqueta', name: 'Motocicleta en banqueta' },
      { code: 'choque_obstruyendo_paso', name: 'Choque que obstruye el paso' },
      { code: 'calle_sin_iluminacion', name: 'Calle sin iluminación' },
      { code: 'bache_peligroso', name: 'Bache o desnivel peligroso' },
      { code: 'construccion_sin_senalizacion', name: 'Construcción sin señalización' },
      { code: 'obstaculos_en_banqueta', name: 'Obstáculos en la banqueta' },
      { code: 'cables_caidos', name: 'Cables caídos' },
      { code: 'alcantarilla_abierta', name: 'Alcantarilla abierta' },
      { code: 'cristales_rotos', name: 'Cristales rotos' },
      { code: 'banqueta_resbalosa', name: 'Banqueta resbalosa' },
      { code: 'autos_invadiendo_banqueta', name: 'Autos invadiendo la banqueta' },
      { code: 'inundacion', name: 'Inundación' },
      { code: 'deslave', name: 'Deslave' },
      { code: 'arbol_caido', name: 'Árbol caído' },
      { code: 'humo_incendio_cercano', name: 'Humo o incendio cercano' },
      { code: 'clima_extremo', name: 'Clima extremo' },
      { code: 'grupo_sospechoso', name: 'Grupo sospechoso bloqueando el paso' },
      { code: 'persona_drogada_alcoholizada', name: 'Persona drogada o alcoholizada' },
      { code: 'rina_cercana', name: 'Riña cercana' },
      { code: 'manifestacion_o_bloqueo', name: 'Manifestación o bloqueo' },
      { code: 'disturbios', name: 'Disturbios o gritos' },
      { code: 'incendio_cercano', name: 'Incendio cercano' },
      { code: 'explosion', name: 'Explosión' },
      { code: 'fuga_de_gas', name: 'Fuga de gas' },
      { code: 'cortocircuito', name: 'Cortocircuito en poste' },
      { code: 'emergencia_medica', name: 'Emergencia médica en la vía pública' },
    ])
  }
}
